package com.wealthtech.crm.infrastructure.ai.security;

import java.util.Collections;
import java.util.Map;

/**
 * Immutable carrier for PII-sanitized text and its ephemeral request-scoped token vault.
 * Contains backward-pass de-tokenization / rehydration logic.
 */
public record PiiTokenizationResult(
        String sanitizedText,
        Map<String, String> tokenVault
) {
    public PiiTokenizationResult {
        tokenVault = (tokenVault != null) ? Collections.unmodifiableMap(tokenVault) : Collections.emptyMap();
    }

    /**
     * Backward pass: Re-hydrates surrogate tokens back to their authentic values.
     *
     * @param responseText Text generated by the LLM containing surrogate tokens (e.g. {{CLIENT_NAME_1}})
     * @return Fully re-hydrated text with original PII restored.
     */
    public String rehydrate(String responseText) {
        if (responseText == null || responseText.isBlank() || tokenVault.isEmpty()) {
            return responseText;
        }

        String result = responseText;
        for (Map.Entry<String, String> entry : tokenVault.entrySet()) {
            result = result.replace(entry.getKey(), entry.getValue());
        }
        return result;
    }
}
